### ISSUE TITLE
multiple attack don't make effert on such as: slm bloom

### ISSUE THREAD

**Issue by restarteded** [Akebi-Group/Akebi-GC#507] opened 2022-08-25 11:01 UTC

**Comment by Taiga74164** [comment] 2022-08-25 20:29
slm bloom?

**Comment by keexers** [comment] 2022-08-28 06:15
> slm bloom? your title doesn't tell me how to reproduce this issue?

he means the slime balloon which usually appears on daily commissions

**Comment by Taiga74164** [comment] 2022-08-28 06:18
duplicate of #16

**Closed by Taiga74164** 2022-08-28 06:18 UTC
Labels: Duplicate, Enhancement
