### ISSUE TITLE
Game Frozen in Character Menu

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#34] opened 2022-05-25 18:32 UTC
IDK this is cheat bug or game, BUT this bug occurs only TODAY, (Before everything will be fine).
When swap characters some of 3-7 times game frozen and crash (Not responding statue).

I mean this menu:
![image](https://user-images.githubusercontent.com/104440397/170340703-cf8f7567-3331-4b35-b8f3-cb448ba78e3e.png)

Active Cheats on Screenshoot.
Cheat itself not writes any related to console i think some type of memory leak occurs.

Commit - Latest. (ReleaseWS)

**Comment by Taiga74164** [comment] 2022-08-25 20:39
closing this since it's old and I can't seem to reproduce this issue with the latest build. let me know if it occurs again or re-open this issue

**Closed by Taiga74164** 2022-08-25 20:39 UTC
Labels: Bug
