### ISSUE TITLE
Auto pick-up randomly stops working

### ISSUE THREAD

**Issue by GarethOz** [Akebi-Group/Akebi-GC#28] opened 2022-05-22 19:16 UTC
Auto pick-up sometimes stops working and you have to pick an item manually so that it continues working again.

**Comment by Taiga74164** [comment] 2022-08-25 20:38
closing this since it's old and I can't seem to reproduce this issue with the latest build. let me know if it occurs again or re-open this issue

**Closed by Taiga74164** 2022-08-25 20:38 UTC
Labels: Bug
