### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by 3321420198** [Akebi-Group/Akebi-GC#688] opened 2022-09-16 10:40 UTC
## Describe the problem 

Please fill in here a clear and accurate description of the problem you are experiencing.
The VS2022 compilation failed.
## How to reproduce this problem

Steps to reproduce this issue:
1. 下载SV2022克隆
2. Download SV2022 clone and then prompt failure
3. xxxxxx
4. xxxxxxxx

## Help you need

Please fill in the help you need here.
Can you help me solve it?
## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.
![image](https://user-images.githubusercontent.com/49073387/190620823-f503b762-bcf0-4f57-bf3f-0996d3d0e137.png)
![image](https://user-images.githubusercontent.com/49073387/190620861-cfbb79e4-f9e8-4275-bcb9-03face18f675.png)
![image](https://user-images.githubusercontent.com/49073387/190620945-64e68092-0d65-4d70-9480-52e62d87e105.png)

## Your device information
Windows professional edition1909
 
 - Version:

## Additional information

Here you can enter additional information about the help you need.

**Comment by m0nkrel** [comment] 2022-09-16 10:42
How did you clone the repository?

**Comment by 3321420198** [comment] 2022-09-16 10:47
> 您是如何克隆存储库的？

![image](https://user-images.githubusercontent.com/49073387/190622413-09aff239-ee49-4973-ada9-d078b5de14dd.png)

**Comment by m0nkrel** [comment] 2022-09-16 11:02
cloned same way as you, works fine
![image](https://user-images.githubusercontent.com/84017229/190624953-b3da0cf3-7945-4727-9af0-a22597dbec94.png)

**Comment by Shichiha** [comment] 2022-09-16 11:18
Duplicate of closed issues #61, #52, #54, #175, #184, #201, #450

**Comment by 3321420198** [comment] 2022-09-16 14:07
> Duplicate of closed issues #61, #52, #54, #175, #184, #201, #450

![image](https://user-images.githubusercontent.com/49073387/190658346-64172520-1db2-4d06-ad30-f482456af0d6.png)
![image](https://user-images.githubusercontent.com/49073387/190658397-ca11056f-3e4a-41fb-aac0-e27563787a38.png)

**Comment by Taiga74164** [comment] 2022-09-16 14:10
Read what the warning says. Switch to chinese branch

**Closed by Taiga74164** 2022-09-16 14:10 UTC
Labels: Help Wanted

**Comment by 3321420198** [comment] 2022-09-16 14:15
> 阅读警告内容。切换到中文分支

I didn't catch what you said.

> Read what the warning says. Switch to chinese branch

I didn't catch what you said.

**Comment by xTaiwanPingLord** [comment] 2022-09-16 15:55
> > 阅读警告内容。切换到中文分支
> 
> I didn't catch what you said.
> 
> > Read what the warning says. Switch to chinese branch
> 
> I didn't catch what you said.

If you're using chinese version of genshin impact, please switch to upstream/chinese branch in vs2022.
如果你用的是國服不是國際服，你要在VS2022右下角切換到upstream/chinese分支


![image](https://user-images.githubusercontent.com/52948923/190680284-c2b86c94-cac3-4054-aa2c-e27bfdc32b46.png)
