### ISSUE TITLE
`Interactive map` crash

### ISSUE THREAD

**Issue by Skript1X** [Akebi-Group/Akebi-GC#9] opened 2022-05-18 10:16 UTC
Date Occured: 18.05.2022
Is it reproducible: Yes
Release Version: 0.7

The bug is reproduced when you close the map with the interactive map tab open enabled
At the same time, if saving the cheat configuration is enabled, then the next time the cheat is launched, it will simply not be injected into the game
But after that if you delete cfg.json and cfg.ini then the cheat will be injected into the game

Video proof: https://mega.nz/file/Gq5V0IyC#C0nOIyvsz5FWw6-uHGz0qGrFjIkrwZ9vd7sBLcwT6Qo

**Comment by CallowBlack** [comment] 2022-05-18 19:12
Can you send me your `cfg.json` file after the crash

**Comment by Skript1X** [comment] 2022-05-19 07:56
> Can you send me your `cfg.json` file after the crash?

[https://mega.nz/file/DiB0yaoR#DJCOj3qcKftrI5I72mRIXQa8Q_hEj4MOn_zSj1zo8XI](url)

**Comment by Taiga74164** [comment] 2022-09-03 02:24
I just tried your config and it seems fine. I'm closing this issue since its old and I can't reproduce your issue. If you encounter this issue again, feel free to re-open it and let me know

**Closed by Taiga74164** 2022-09-03 02:24 UTC
Labels: Bug, Client Problem
