### ISSUE TITLE
UI Bug after enter the chasm underground

### ISSUE THREAD

**Issue by heinzrommel** [Akebi-Group/Akebi-GC#66] opened 2022-06-01 04:18 UTC
![Screenshot_91](https://user-images.githubusercontent.com/93069552/171326607-02de12be-40f1-4e38-a4b0-f4b2f77e7fdf.png)
![Screenshot_92](https://user-images.githubusercontent.com/93069552/171326616-6a9de2e2-eaf5-48f3-9e02-8254f712c6e9.png)

**Comment by Shichiha** [comment] 2022-06-01 04:32
duplicate of #15

**Closed** 2022-06-02 11:27 UTC
Labels: bug, duplicate
