### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Classified745** [Akebi-Group/Akebi-GC#84] opened 2022-06-06 04:10 UTC
I encountered this bug in the Multi-Hit Mode function. When the same value is set, the game crashes.

This problem is related to CLibrary. I think that in Multi-hit you need to add a variable check function so that when entering the same values, Multi-hit multiplies the hits by one variable, and does not randomize it in a range of two numbers.

[Link to the video](https://cloud.mail.ru/public/kPJm/ZcEXk6Btm)

**Comment by WitchGod** [comment] 2022-06-06 06:32
No need to open another issue, just search the other one and add it to there.

Yes, it's because there's a range calculator for randomized. Should be fixed by adding a line that checks `if min == max return min` or something like that.

**Comment by CallowBlack** [comment] 2022-06-10 00:12
Duplicate of #82

**Closed by CallowBlack** 2022-06-10 00:12 UTC
