### ISSUE TITLE
`Interactive map` don't detect oculies

### ISSUE THREAD

**Issue by Kaephrodite** [Akebi-Group/Akebi-GC#13] opened 2022-05-19 01:53 UTC
the interactive map didnt detect the taken item or the item that i havent take the logo just the same and i dont know how to make this normal again please help

**Comment by Taiga74164** [comment] 2022-05-19 02:06
its the same concept as an actual Interactive Map you'll find in the web.

**Comment by souvikpodder** [comment] 2022-05-19 03:47
> the interactive map didnt detect the taken item or the item that i havent take the logo just the same and i dont know how to make this normal again please help

For the items that doesn't have auto detect. Right click on the icon after opening the map it will complete that item.

**Comment by Kaephrodite** [comment] 2022-05-19 04:16
> > the interactive map didnt detect the taken item or the item that i havent take the logo just the same and i dont know how to make this normal again please help
> 
> For the items that doesn't have auto detect. Right click on the icon after opening the map it will complete that item.



> > the interactive map didnt detect the taken item or the item that i havent take the logo just the same and i dont know how to make this normal again please help
> 
> For the items that doesn't have auto detect. Right click on the icon after opening the map it will complete that item.

well im collecting oculi

**Comment by Kaephrodite** [comment] 2022-05-19 04:18
> its the same concept as an actual Interactive Map you'll find in the web. don't expect it to know if you already have or have not picked up a certain item

im collecting oculi

**Comment by Kaephrodite** [comment] 2022-05-19 04:18
> > the interactive map didnt detect the taken item or the item that i havent take the logo just the same and i dont know how to make this normal again please help
> 
> For the items that doesn't have auto detect. Right click on the icon after opening the map it will complete that item.

well im collecting oculi that have auto detect

**Comment by CallowBlack** [comment] 2022-05-19 22:37
Can you capture video with the problem?

**Comment by Taiga74164** [comment] 2022-08-25 20:41
closing this since it's old and I can't seem to reproduce this issue with the latest build. let me know if it occurs again or re-open this issue

**Closed by Taiga74164** 2022-08-25 20:41 UTC
Labels: Bug
