### ISSUE TITLE
first start Crashed :) 

### ISSUE THREAD

**Issue by Rizky0321** [Akebi-Group/Akebi-GC#259] opened 2022-07-13 15:35 UTC
![Desktop Screenshot 2022 07 13 - 22 34 36 07](https://user-images.githubusercontent.com/109232797/178773482-12cd07ab-a05e-4015-8d2a-3b1ee4fe04d2.png)
fix this hehe

**Comment by Rizky0321** [comment] 2022-07-13 15:36
i use version windows 10 20h
![Desktop Screenshot 2022 07 13 - 22 30 02 22](https://user-images.githubusercontent.com/109232797/178773753-902ac5a8-df7d-42f1-962e-d21aeace8a09.png)
2

**Comment by beckgreen** [comment] 2022-07-13 16:00
me too

**Comment by tedzify** [comment] 2022-07-13 16:52
Duplicate of #252. No need to open an existing issue.

**Closed** 2022-07-13 17:28 UTC
Labels: duplicate, crash
