### ISSUE TITLE
An error occurred trying to build the latest version

### ISSUE THREAD

**Issue by ArgonCrystal** [Akebi-Group/Akebi-GC#450] opened 2022-08-11 07:25 UTC
build use：Microsoft Visual Studio Community 2022 (x64) - Current version 17.3.0
Visual Studio error message 
error 	C1083	Unable to open include file: “magic_enum.hpp”: No such file or directory	cheat-base	D:\Documents\GitHub\Akebi-GC\cheat-base\framework\pch.h	13	
error 	C1083	Unable to open include file: “SimpleIni.h”: No such file or directory	injector	D:\Documents\GitHub\Akebi-GC\cheat-base\src\cheat-base\util.h	10	
error 	C1083	Unable to open include file: “SimpleIni.h”: No such file or directory	injector	D:\Documents\GitHub\Akebi-GC\injector\src\main.cpp	6	
error 	C1083	Unable to open include file: “SimpleIni.h”: No such file or directory	injector	D:\Documents\GitHub\Akebi-GC\cheat-base\src\cheat-base\util.h	10	
error 	C1083	Unable to open include file: “nlohmann/json.hpp”: No such file or directory	cheat-library	D:\Documents\GitHub\Akebi-GC\cheat-library\src\framework\pch-il2cpp.h	13

**Comment by tedzify** [comment] 2022-08-11 07:44
Here you go, watch this: https://www.youtube.com/watch?v=vwMT5iwVe9g

Or just download the latest commit from [Actions](https://github.com/Akebi-Group/Akebi-GC/actions).

**Comment by Shichiha** [comment] 2022-08-11 10:09
Duplicate of closed issues #61, #52, #54, #175, #184, #201

**Closed** 2022-08-13 04:30 UTC
