### ISSUE TITLE
screen bug

### ISSUE THREAD

**Issue by fid3n** [Akebi-Group/Akebi-GC#89] opened 2022-06-07 01:11 UTC
i was playing and doing quests and this happend
![image](https://user-images.githubusercontent.com/102911531/172274429-268aa0c8-3a74-41ce-bbec-0865466fd687.png)
![image](https://user-images.githubusercontent.com/102911531/172274458-c6cbff10-32f7-46d5-8df6-e18187b97385.png)

P>S>

i was using fast dialog+auto-select and i think it broke my screen

p>S>S>

with gen.xyz all was perfect

**Comment by G1DE30N** [comment] 2022-06-07 05:01
Duplicate of tons of other issues, in this state considered Non-fixible.

**Closed** 2022-06-07 11:00 UTC
