### ISSUE TITLE
UI getting messed up

### ISSUE THREAD

**Issue by GarethOz** [Akebi-Group/Akebi-GC#37] opened 2022-05-26 20:35 UTC
I don't know if this is from the program or the game itself.
![image](https://user-images.githubusercontent.com/104610042/170575693-f76f94aa-8861-4ba2-8c97-88a87820beb7.png)

**Comment by Fractune** [comment] 2022-05-26 20:50
I got this issue as well when I entered The Chasm or teleported while I was in there, I don't recall exactly how I produced that.

**Comment by CallowBlack** [comment] 2022-05-26 21:00
Duplicate of #15

**Closed by CallowBlack** 2022-05-26 21:00 UTC
Labels: bug, duplicate
