### ISSUE TITLE
Title: “Infinite Stamina“  (Genshin Impact)

### ISSUE THREAD

**Issue by Badsha71** [Akebi-Group/Akebi-GC#122] opened 2022-06-16 20:36 UTC
Description: “Game crashed if my network reconnect the game"... after my game get online in few second then the infinite stamina don't work even if i off this option my game key also not working for sprenting,,after i off all the active cheat and then close my game and open it again from ijector then it get fixed and work.sprint also not working after relogin if game closed with turned on cheat.

**Comment by Shichiha** [comment] 2022-06-17 20:56
Might be a duplicate of #42

**Comment by Badsha71** [comment] 2022-06-18 02:55
Yes i got it,does it will get fixed ?

**Closed** 2022-06-18 03:02 UTC
