### ISSUE TITLE
Mona - Infinite Stamina - Not Working

### ISSUE THREAD

**Issue by LokeYourLord** [Akebi-Group/Akebi-GC#294] opened 2022-07-16 02:01 UTC
What the title says. With Mona, Infinite Stamina doesn't seem to work as it gets drained regardless when sprinting over land or water. Any way of fixing this? I use the "Move Sync Packet Replacement" mode, because I don't want to risk using the regular variant. That being said, I quickly tried it with the regular variant and it does work with that one, so the issue is with the "Move Sync Packet Replacement" version. Also, with the regular version, it only works on land. Once you start going over onto water, you drown. So both are broken but in different ways.

**Comment by Taiga74164** [comment] 2022-07-16 02:47
Known issue. duplicate of #11

**Closed** 2022-07-16 02:47 UTC
Labels: bug
