### ISSUE TITLE
no-Clip

### ISSUE THREAD

**Issue by qiaozhi-4** [Akebi-Group/Akebi-GC#358] opened 2022-07-24 23:13 UTC
Can't talk when the no-clip function is turned on

**Comment by zhouqingyi1127** [comment] 2022-07-24 23:56
我的也是

**Comment by EchoesFromBeyond** [comment] 2022-07-25 00:01
This is a known bug, please read through the Issues before submitting new ones. It usually is fixed by restarting. Sometimes you will get into a bugged state.

**Comment by qiaozhi-4** [comment] 2022-07-25 00:09
> fixed

ok
好的👌🏻

**Comment by Taiga74164** [comment] 2022-07-25 03:03
duplicate of #32

**Closed** 2022-07-25 03:03 UTC
Labels: bug, duplicate
