### ISSUE TITLE
Bug "God Mode"

### ISSUE THREAD

**Issue by Viole403** [Akebi-Group/Akebi-GC#86] opened 2022-06-06 11:14 UTC
After trying this feature I found a bug, "HP" keeps decreasing when "Sheer cold" indicator is full in Dragonspine area

**Comment by CNLouisLiu** [comment] 2022-06-06 14:03
God mode, not immune to cold and lightning damage.

**Comment by G1DE30N** [comment] 2022-06-08 22:05
> After trying this feature I found a bug, "HP" keeps decreasing when "Sheer cold" indicator is full in Dragonspine area

Godmode not designed for that type of damage. Taiga once implemented and commented a piece of code which can do that but in 2.7 this code not worked anymore. I requested that feature but not achieve any info about this feature will be implemented or not in future.

**Comment by CallowBlack** [comment] 2022-06-10 00:13
Duplicate of #60

**Closed by CallowBlack** 2022-06-10 00:13 UTC
Labels: duplicate, enhancement
