### ISSUE TITLE
Visual Studio build error

### ISSUE THREAD

**Issue by tayhm0817** [Akebi-Group/Akebi-GC#48] opened 2022-05-31 08:26 UTC
![image](https://user-images.githubusercontent.com/104625131/171128107-9ede0219-4d6e-47bb-9755-88fe8703ca78.png)
any idea why is this happening?

**Comment by tayhm0817** [comment] 2022-05-31 08:26
i was not able to build the solution

**Comment by CallowBlack** [comment] 2022-05-31 08:31
Seems like you have no `C++ standard library`

**Comment by tayhm0817** [comment] 2022-05-31 08:38
hi how do i get it?

**Comment by G1DE30N** [comment] 2022-05-31 09:09
If that you help (because again in russian) here
![image](https://user-images.githubusercontent.com/104440397/171137555-f88a9ac6-315b-4c1b-9109-1de15258bd7f.png)

**Comment by tayhm0817** [comment] 2022-05-31 09:18
![image](https://user-images.githubusercontent.com/104625131/171139268-e08d56cb-fc6c-437b-881a-5b7a5682652d.png)
yep i do like yours alr but it still show error

**Comment by G1DE30N** [comment] 2022-05-31 09:23
> ![image](https://user-images.githubusercontent.com/104625131/171139268-e08d56cb-fc6c-437b-881a-5b7a5682652d.png)
> yep i do like yours alr but it still show error

First of all ignore all warnings.
Second get the source code correctly.
And then correctly compile it.

Use Git in vs and clone repo. Wait untill it is done and then open AkebiGI.sln with double click in right panel, then go to build and select Batch building. Select only Release for Cheat Base, Cheat Library, and Injector, then press build.

**Comment by tayhm0817** [comment] 2022-05-31 09:30
it works now thank you so much

**Comment by tayhm0817** [comment] 2022-05-31 09:30
just a question why cant i just press build for the solution instead of batch build

**Comment by tayhm0817** [comment] 2022-05-31 09:37
thank you so much

**Comment by Legend-Recalls** [comment] 2022-05-31 09:39
if the issue is solved please consider closing this thread

**Closed** 2022-05-31 09:47 UTC
Labels: client problem
