### ISSUE TITLE
Is it possible to remove completed time trial from ESP?

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#571] opened 2022-08-28 18:39 UTC
Whether it's completed or not, it still shows up in the esp so I came up with an idea
There's a red mark thingy above the time trial indicating if it's completed or not, would it be possible to use that to differentiate between completed and uncompleted ones?

**Comment by Taiga74164** [comment] 2022-08-28 18:40
was working in this with @m0nkrel but there were some in issues

**Comment by Taiga74164** [comment] 2022-08-28 20:41
also duplicate of #345

**Closed by Taiga74164** 2022-08-28 20:41 UTC
Labels: Duplicate, Enhancement
