### ISSUE TITLE
Interactive Map For Golden Apple Archipelago

### ISSUE THREAD

**Issue by GlacyAnimeLover** [Akebi-Group/Akebi-GC#288] opened 2022-07-15 19:04 UTC
Interactive Map For Golden Apple Archipelago with filters for chest, puzzle, conches, etc for easy exploration...

**Comment by Taiga74164** [comment] 2022-07-15 19:06
duplicate of #285 and being reviewed at #287

**Closed** 2022-07-15 19:06 UTC
Labels: duplicate, enhancement
